Add -Wno-unused-parameter to suppress the warning.
For example in system/core/libcorkscrew/arch-arm/backtrace-arm.c:

system/core/libcorkscrew/arch-arm/backtrace-arm.c:555:49: error: unused
parameter 'siginfo' [-Werror=unused-parameter]

Change-Id: Ibe13e8761a2f57324c0f0d87d9add549a20aa37a